"""Build normalized text chunks from the site data.

Reads _site/ai-search.json (generated by `bundle exec jekyll build`) if it
exists, otherwise falls back to reading the source markdown files directly
via the SiteIndex loader in mcp/site_index.py.

Output: rag/index/chunks.json
Each chunk has:
  id          – stable unique identifier
  title       – page/entity title
  url         – canonical URL
  entity_type – course | person | group | program | page | post
  text        – searchable text body
  keywords    – list[str] (may be empty)
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
SITE_JSON = REPO_ROOT / "_site" / "ai-search.json"
CHUNKS_OUT = REPO_ROOT / "rag" / "index" / "chunks.json"
SITE_URL = "https://www.cs.umb.edu"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _collapse(text: str | None) -> str:
    return re.sub(r"\s+", " ", text or "").strip()


def _join(*parts: str | list[str] | None) -> str:
    tokens: list[str] = []
    for part in parts:
        if isinstance(part, list):
            tokens.extend(str(p) for p in part if p)
        elif part:
            tokens.append(str(part))
    return " ".join(t.strip() for t in tokens if t.strip())


def _make_url(path: str | None) -> str:
    if not path:
        return SITE_URL
    if path.startswith("http"):
        return path
    return SITE_URL + ("" if path.startswith("/") else "/") + path


# ---------------------------------------------------------------------------
# Source: _site/ai-search.json (post-Jekyll build)
# ---------------------------------------------------------------------------

def _chunks_from_site_json(data: dict[str, Any]) -> list[dict[str, Any]]:
    chunks: list[dict[str, Any]] = []

    # Pages
    for page in data.get("pages", []):
        url = page.get("url") or ""
        title = _collapse(page.get("title"))
        text = _join(
            title,
            page.get("summary"),
            page.get("description"),
            page.get("content_excerpt"),
        )
        chunks.append({
            "id": f"page:{url}",
            "title": title,
            "url": url,
            "entity_type": "page",
            "text": _collapse(text),
            "keywords": page.get("keywords") or [],
        })

    # Courses
    for course in data.get("courses", []):
        code = _collapse(course.get("course_code"))
        name = _collapse(course.get("course_name") or course.get("title"))
        url = course.get("url") or ""
        prereqs = course.get("prerequisites") or []
        text = _join(
            code, name,
            course.get("summary"),
            course.get("description"),
            "Prerequisites: " + ", ".join(prereqs) if prereqs else None,
            course.get("content_excerpt"),
        )
        kw = list(course.get("keywords") or [])
        if code:
            kw.insert(0, code)
        chunks.append({
            "id": f"course:{code}",
            "title": f"{code} {name}".strip(),
            "url": url,
            "entity_type": "course",
            "text": _collapse(text),
            "keywords": kw,
            "course_code": code,
            "prerequisites": prereqs,
        })

    # Programs
    for prog in data.get("programs", []):
        url = prog.get("url") or ""
        title = _collapse(prog.get("title"))
        text = _join(
            title,
            prog.get("summary"),
            prog.get("description"),
            prog.get("content_excerpt"),
        )
        chunks.append({
            "id": f"program:{url}",
            "title": title,
            "url": url,
            "entity_type": "program",
            "text": _collapse(text),
            "keywords": prog.get("keywords") or [],
        })

    # People
    for person in data.get("people", []):
        url = person.get("url") or ""
        name = _collapse(person.get("person_name") or person.get("title"))
        research = person.get("research_areas") or []
        text = _join(
            name,
            person.get("job_title"),
            person.get("summary"),
            person.get("description"),
            "Research areas: " + ", ".join(research) if research else None,
            person.get("content_excerpt"),
        )
        kw = list(person.get("keywords") or [])
        kw += research
        chunks.append({
            "id": f"person:{person.get('slug', url)}",
            "title": name,
            "url": url,
            "entity_type": "person",
            "text": _collapse(text),
            "keywords": list(dict.fromkeys(kw)),
        })

    # Groups
    for group in data.get("groups", []):
        url = group.get("url") or ""
        name = _collapse(group.get("group_name") or group.get("title"))
        topics = group.get("related_topics") or []
        text = _join(
            name,
            group.get("summary"),
            group.get("description"),
            "Topics: " + ", ".join(topics) if topics else None,
            group.get("content_excerpt"),
        )
        chunks.append({
            "id": f"group:{group.get('slug', url)}",
            "title": name,
            "url": url,
            "entity_type": "group",
            "text": _collapse(text),
            "keywords": topics,
        })

    return chunks


# ---------------------------------------------------------------------------
# Source: direct markdown reading via SiteIndex (fallback)
# ---------------------------------------------------------------------------

def _chunks_from_site_index() -> list[dict[str, Any]]:
    sys.path.insert(0, str(REPO_ROOT))
    from mcp.site_index import SiteIndex  # type: ignore[import]

    idx = SiteIndex(REPO_ROOT)
    chunks: list[dict[str, Any]] = []

    # Courses
    for course in idx.courses:
        code = course.get("course_code", "")
        name = _collapse(course.get("course_name") or course.get("title"))
        prereqs = course.get("prerequisites") or []
        url = _make_url(course.get("permalink"))
        text = _join(
            code, name,
            course.get("summary"),
            course.get("description"),
            "Prerequisites: " + ", ".join(prereqs) if prereqs else None,
            course.get("content_excerpt"),
        )
        kw = list(course.get("keywords") or [])
        if code:
            kw.insert(0, code)
        chunks.append({
            "id": f"course:{code}",
            "title": f"{code} {name}".strip(),
            "url": url,
            "entity_type": "course",
            "text": _collapse(text),
            "keywords": kw,
            "course_code": code,
            "prerequisites": prereqs,
        })

    # People
    for person in idx.people:
        slug = person.get("slug", "")
        name = _collapse(person.get("person_name") or person.get("title"))
        research = person.get("research_areas") or []
        url = _make_url(person.get("permalink"))
        text = _join(
            name,
            person.get("job_title"),
            person.get("summary"),
            person.get("description"),
            "Research areas: " + ", ".join(research) if research else None,
            person.get("content_excerpt"),
        )
        kw = list(person.get("keywords") or [])
        kw += research
        chunks.append({
            "id": f"person:{slug}",
            "title": name,
            "url": url,
            "entity_type": "person",
            "text": _collapse(text),
            "keywords": list(dict.fromkeys(kw)),
        })

    # Groups
    for group in idx.groups:
        slug = group.get("slug", "")
        name = _collapse(group.get("group_name") or group.get("title"))
        topics = group.get("related_topics") or []
        url = _make_url(group.get("permalink"))
        text = _join(
            name,
            group.get("summary"),
            group.get("description"),
            "Topics: " + ", ".join(topics) if topics else None,
            group.get("content_excerpt"),
        )
        chunks.append({
            "id": f"group:{slug}",
            "title": name,
            "url": url,
            "entity_type": "group",
            "text": _collapse(text),
            "keywords": topics,
        })

    # Pages & programs
    for page in idx.pages:
        slug = page.get("slug", "")
        url = _make_url(page.get("permalink"))
        title = _collapse(page.get("title"))
        etype = page.get("entity_type", "page")
        text = _join(
            title,
            page.get("summary"),
            page.get("description"),
            page.get("content_excerpt"),
        )
        chunks.append({
            "id": f"{etype}:{slug}",
            "title": title,
            "url": url,
            "entity_type": etype,
            "text": _collapse(text),
            "keywords": list(page.get("keywords") or []),
        })

    # Posts
    for post in idx.posts:
        slug = post.get("slug", "")
        url = _make_url(post.get("permalink"))
        title = _collapse(post.get("title"))
        text = _join(title, post.get("summary"), post.get("content_excerpt"))
        chunks.append({
            "id": f"post:{slug}",
            "title": title,
            "url": url,
            "entity_type": "post",
            "text": _collapse(text),
            "keywords": list(post.get("keywords") or []),
        })

    return chunks


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def build_chunks() -> list[dict[str, Any]]:
    if SITE_JSON.exists():
        print(f"Loading from {SITE_JSON} …")
        data = json.loads(SITE_JSON.read_text(encoding="utf-8"))
        chunks = _chunks_from_site_json(data)
        source = "Jekyll build (_site/ai-search.json)"
    else:
        print(f"{SITE_JSON} not found – falling back to source markdown files …")
        print("Run `bundle exec jekyll build` first for the best results.")
        chunks = _chunks_from_site_index()
        source = "source markdown files (mcp/site_index.py)"

    # Drop empty chunks
    chunks = [c for c in chunks if c.get("text", "").strip()]

    # Deduplicate by id
    seen: set[str] = set()
    deduped: list[dict[str, Any]] = []
    for chunk in chunks:
        if chunk["id"] not in seen:
            seen.add(chunk["id"])
            deduped.append(chunk)

    CHUNKS_OUT.parent.mkdir(parents=True, exist_ok=True)
    CHUNKS_OUT.write_text(json.dumps(deduped, indent=2, ensure_ascii=False), encoding="utf-8")

    print(f"Wrote {len(deduped)} chunks → {CHUNKS_OUT}  (source: {source})")
    return deduped


if __name__ == "__main__":
    build_chunks()
